name: Sync torneo_uruguay_open_cup_2v2.json to civs repo

on:
  push:
    paths:
      - torneos/torneo_uruguay_open_cup_2v2.json  # Ejecuta solo si este archivo cambia

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio privado (bot-fmg)
        uses: actions/checkout@v3

      - name: Clonar repositorio público (civs)
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git clone https://x-access-token:${{ secrets.PUBLIC_REPO_TOKEN }}@github.com/Alegenio2/civs.git
          cp torneos/torneo_uruguay_open_cup_2v2.json civs/torneos/
          cd civs
          git add torneos/torneo_uruguay_open_cup_2v2.json
          git commit -m "Sync automático de torneo_uruguay_open_cup_2v2.json desde bot-fmg" || echo "Sin cambios"
          git push
